######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : dm-process, Index = 0, Count = null
# SUBMIT FILE NAME : cleanup_dm-process_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin PYTHONPATH=/usr/lib/pegasus/python CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=8454928b-a095-4148-9cf3-b2a788f4738b PEGASUS_WF_LABEL=dm-process PEGASUS_DAG_JOB_ID=cleanup_dm-process_0_local PEGASUS_SITE=local _PEGASUS_WF_SUBMIT_DIR=/home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/process-same-w1-20260917-232331/luis/pegasus/dm-process/run0001 PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::cleanup -N null -i - -R local  -L dm-process -T 2026-09-17T23:23:31-05:00 pegasus-transfer "
error = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/process-same-w1-20260917-232331/luis/pegasus/dm-process/run0001//00/00/cleanup_dm-process_0_local.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/process-same-w1-20260917-232331/luis/pegasus/dm-process/run0001//00/00/cleanup_dm-process_0_local.in
log = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/process-same-w1-20260917-232331/luis/pegasus/dm-process/run0001/dm-process-0.log
notification = NEVER
output = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/process-same-w1-20260917-232331/luis/pegasus/dm-process/run0001//00/00/cleanup_dm-process_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
wf_submit_dir = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/process-same-w1-20260917-232331/luis/pegasus/dm-process/run0001
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "8454928b-a095-4148-9cf3-b2a788f4738b"
+pegasus_wf_uuid = "8454928b-a095-4148-9cf3-b2a788f4738b"
+pegasus_version = "5.1.2"
+pegasus_wf_name = "dm-process-0"
+pegasus_wf_time = "20260917T232333-0500"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_dm-process_0_local"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
