######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : dm-pipeline, Index = 0, Count = null
# SUBMIT FILE NAME : stage_out_local_local_2_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin PYTHONPATH=/usr/lib/pegasus/python CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=dbd362d5-f632-45c8-b822-920164630c49 PEGASUS_WF_LABEL=dm-pipeline PEGASUS_DAG_JOB_ID=stage_out_local_local_2_0 PEGASUS_SITE=local _PEGASUS_WF_SUBMIT_DIR=/home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-balanced-local-20260917-232616/luis/pegasus/dm-pipeline/run0001 _PEGASUS_TRANSFER_INPUT_FILES=$(wf_submit_dir)/00/00/data_task_ID0000003.meta, PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "/usr/bin/../bin/pegasus-kickstart  -n pegasus::transfer -N null -i - -R local  -L dm-pipeline -T 2026-09-17T23:26:16-05:00 /usr/bin/../bin/pegasus-transfer  --threads 2 "
error = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-balanced-local-20260917-232616/luis/pegasus/dm-pipeline/run0001//00/00/stage_out_local_local_2_0.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-balanced-local-20260917-232616/luis/pegasus/dm-pipeline/run0001//00/00/stage_out_local_local_2_0.in
log = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-balanced-local-20260917-232616/luis/pegasus/dm-pipeline/run0001/dm-pipeline-0.log
notification = NEVER
output = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-balanced-local-20260917-232616/luis/pegasus/dm-pipeline/run0001//00/00/stage_out_local_local_2_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 900
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
wf_submit_dir = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-balanced-local-20260917-232616/luis/pegasus/dm-pipeline/run0001
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "dbd362d5-f632-45c8-b822-920164630c49"
+pegasus_wf_uuid = "dbd362d5-f632-45c8-b822-920164630c49"
+pegasus_version = "5.1.2"
+pegasus_wf_name = "dm-pipeline-0"
+pegasus_wf_time = "20260917T232619-0500"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_out_local_local_2_0"
+pegasus_job_class = 3
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
