######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : dm-pipeline, Index = 0, Count = null
# SUBMIT FILE NAME : data_task_ID0000002.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=75042793-dabd-4210-a724-c3e05b5e7287 PEGASUS_WF_LABEL=dm-pipeline PEGASUS_DAG_JOB_ID=data_task_ID0000002 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-cross-20260917-171907/luis/pegasus/dm-pipeline/run0001//00/00/data_task_ID0000002.err
executable = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-cross-20260917-171907/luis/pegasus/dm-pipeline/run0001/00/00/data_task_ID0000002.sh
initialdir = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-cross-20260917-171907/scratch/luis/pegasus/dm-pipeline/run0001
log = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-cross-20260917-171907/luis/pegasus/dm-pipeline/run0001/dm-pipeline-0.log
notification = NEVER
output = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-cross-20260917-171907/luis/pegasus/dm-pipeline/run0001//00/00/data_task_ID0000002.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
request_cpus = 1
request_memory = 256
requirements = regexp("pegasus-worker2", TARGET.Name)
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = pipeline.stage1.dat,data_task,$(wf_submit_dir)/pegasus-worker-5.1.2-x86_64_ubuntu_26.tar.gz,$(wf_submit_dir)/00/00/stage_in_remote_local_0_0.meta,$(wf_submit_dir)/00/00/data_task_ID0000001.meta,$(wf_submit_dir)/pegasus-lite-common.sh
transfer_output_files = pipeline.stage2.dat
universe = vanilla
wf_submit_dir = /home/luis/pegasus-lab/pegasus_avance_semana_1_6/experiments/pipeline-cross-20260917-171907/luis/pegasus/dm-pipeline/run0001
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "75042793-dabd-4210-a724-c3e05b5e7287"
+pegasus_wf_uuid = "75042793-dabd-4210-a724-c3e05b5e7287"
+pegasus_version = "5.1.2"
+pegasus_wf_name = "dm-pipeline-0"
+pegasus_wf_time = "20260917T171908-0500"
+pegasus_wf_xformation = "data_task"
+pegasus_wf_dax_job_id = "ID0000002"
+pegasus_wf_dag_job_id = "data_task_ID0000002"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
